In [2]:
import pandas as pd

from sklearn.preprocessing import MinMaxScaler

In [3]:
fname_url="https://github.com/sipocz/Blood/raw/b5fc44c487b0a712d00865014203349fb8690257/orig/train.zip"
fname=fname_url.split("/")[-1]

In [4]:
!wget $fname_url


--2021-12-05 19:03:57--  https://github.com/sipocz/Blood/raw/b5fc44c487b0a712d00865014203349fb8690257/orig/train.zip
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/sipocz/Blood/b5fc44c487b0a712d00865014203349fb8690257/orig/train.zip [following]
--2021-12-05 19:03:58--  https://raw.githubusercontent.com/sipocz/Blood/b5fc44c487b0a712d00865014203349fb8690257/orig/train.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16979362 (16M) [application/zip]
Saving to: ‘train.zip’

train.zip           100%[===================>]  16.19M  88.8MB/s    in 0.2s    

2021-12-05 19:03:58 (88.8 MB/s) - ‘train.z

In [5]:
!mkdir "train"
!rm ./train/Train.csv

rm: cannot remove './train/Train.csv': No such file or directory


In [6]:
!unzip $fname -d "./train"
!rm train.zip

Archive:  train.zip
  inflating: ./train/Train.csv       


In [7]:
fname_train="./train/Train.csv"
df=pd.read_csv(fname_train)

In [8]:
df.head(5)

Reading_ID  absorbance0  ...  hemoglobin(hgb)_human  cholesterol_ldl_human
0  ID_3SSHI56C     0.479669  ...                     ok                     ok
1  ID_599OOLZA     0.471537  ...                   high                   high
2  ID_MVJGPQ75     0.444998  ...                     ok                   high
3  ID_CK6RF8YV     0.513434  ...                     ok                   high
4  ID_82N6QE6I     0.510485  ...                     ok                   high

[5 rows x 176 columns]

In [9]:
df.columns

Index(['Reading_ID', 'absorbance0', 'absorbance1', 'absorbance2',
       'absorbance3', 'absorbance4', 'absorbance5', 'absorbance6',
       'absorbance7', 'absorbance8',
       ...
       'absorbance165', 'absorbance166', 'absorbance167', 'absorbance168',
       'absorbance169', 'temperature', 'humidity', 'hdl_cholesterol_human',
       'hemoglobin(hgb)_human', 'cholesterol_ldl_human'],
      dtype='object', length=176)

In [10]:
NUM_OF_COMP=3

In [11]:
PCA_X=df.iloc[:,1:-3]

In [15]:
import numpy as np
from sklearn.decomposition import PCA

O_pca = PCA(n_components=NUM_OF_COMP)
O_PCA_values=O_pca.fit_transform(PCA_X,)

print(O_pca.explained_variance_ratio_)

print(O_pca.singular_values_)

[0.88359254 0.10652794 0.00689595]
[935.94477398 324.97950563  82.68396585]


In [16]:
import plotly.express as px

fig = px.scatter(df, x="absorbance82", y="absorbance140",color="hemoglobin(hgb)_human")
fig.show()

In [17]:
import plotly.express as px
opc_df=pd.DataFrame()
opc_df["PCA_x"]=O_PCA_values[:,0]
opc_df["PCA_y"]=O_PCA_values[:,1]
opc_df["color"]=df["hemoglobin(hgb)_human"]


fig = px.scatter(opc_df,x="PCA_x", y="PCA_y",color="color")
fig.show()

In [62]:
import plotly.express as px
opc_df=pd.DataFrame()
opc_df["PCA_x"]=O_PCA_values[:,0]
opc_df["PCA_y"]=O_PCA_values[:,1]
opc_df["color"]=df["hemoglobin(hgb)_human"]
opc_df["labels"]=labels


fig = px.scatter(opc_df,x="PCA_x", y="PCA_y",color="labels")
fig.show()

In [123]:
def label_2_num(label):
    out=[]
    for l in label:
        
        if l=="low":
            o=1
        if l=="ok":
            o=2
        if l=="high":
            o=3
        out.append(o)
        
    return(out)

from sklearn.cluster import DBSCAN
# Compute DBSCAN
dbscan_inp=pd.DataFrame()
dbscan_inp["temperature"]=df["temperature"]
dbscan_inp["humidity"]=df["humidity"]
dbscan_inp["cholesterol_ldl_human"]=label_2_num(list(df["cholesterol_ldl_human"]))
dbscan_inp["hemoglobin(hgb)_human"]=label_2_num(list(df["hemoglobin(hgb)_human"]))




db = DBSCAN(eps=0.85, min_samples=20,).fit(dbscan_inp)
core_samples_mask = np.zeros_like(db.labels_, dtype=bool)
core_samples_mask[db.core_sample_indices_] = True
labels = db.labels_
dbscan_inp["labels"]=labels


fig = px.scatter(dbscan_inp,x="temperature", y="humidity",color="labels",opacity=0.3)
fig2 = px.scatter(dbscan_inp,x="temperature", y="humidity",color="hemoglobin(hgb)_human",opacity=0.3)
fig.show()
fig2.show()


In [105]:
list(df["hemoglobin(hgb)_human"])

['ok',
 'high',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'high',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'high',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'low',
 'ok',
 'low',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'low',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'low',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'high',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'high',
 'ok',
 'ok',
 'high',
 'high',
 'ok',
 'high',
 'ok',
 'ok',
 'ok',
 'high',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'high',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'high',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'high',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'low',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok',
 'ok'

In [111]:
def one_hot_encode_df(df,str_index):
    from sklearn.preprocessing import OneHotEncoder
    indf=df.copy(True)
    one_hot=OneHotEncoder()
    col=indf[str_index].values
    col=col.reshape(-1,1)
    one_hot.fit(col)
    out=one_hot.transform(col).toarray()
    codes=one_hot.get_feature_names()
    print(codes)
    for ind,code in enumerate(codes):
        print("Itt:",ind,codes[ind])
        indf[str_index+"_"+code]=out[:,ind]
    return(indf,one_hot)


In [112]:
hdl_col_df,hdl_onehot=one_hot_encode_df(df,"hdl_cholesterol_human")
hemo_df,hemo_onehot=one_hot_encode_df(df,"hemoglobin(hgb)_human")
col_df,col_onehot=one_hot_encode_df(df,"cholesterol_ldl_human")

['x0_high' 'x0_low' 'x0_ok']
Itt: 0 x0_high
Itt: 1 x0_low
Itt: 2 x0_ok
['x0_high' 'x0_low' 'x0_ok']
Itt: 0 x0_high
Itt: 1 x0_low
Itt: 2 x0_ok
['x0_high' 'x0_low' 'x0_ok']
Itt: 0 x0_high
Itt: 1 x0_low
Itt: 2 x0_ok


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [113]:
hemo_df.tail()

Reading_ID  ...  hemoglobin(hgb)_human_x0_ok
13135  ID_NGPC0DA3  ...                          1.0
13136  ID_XRBUD5U8  ...                          1.0
13137  ID_2M9L5NV2  ...                          1.0
13138  ID_C5V5SD2D  ...                          1.0
13139  ID_9R5ZR9NX  ...                          1.0

[5 rows x 179 columns]

In [114]:
del hdl_col_df["hdl_cholesterol_human"]
del hdl_col_df["hemoglobin(hgb)_human"]
del hdl_col_df["cholesterol_ldl_human"]
del hemo_df["hdl_cholesterol_human"]
del hemo_df["hemoglobin(hgb)_human"]
del hemo_df["cholesterol_ldl_human"]
del col_df["hdl_cholesterol_human"]
del col_df["hemoglobin(hgb)_human"]
del col_df["cholesterol_ldl_human"]




In [115]:
hdl_col_df.head()

Reading_ID  ...  hdl_cholesterol_human_x0_ok
0  ID_3SSHI56C  ...                          1.0
1  ID_599OOLZA  ...                          1.0
2  ID_MVJGPQ75  ...                          1.0
3  ID_CK6RF8YV  ...                          0.0
4  ID_82N6QE6I  ...                          1.0

[5 rows x 176 columns]

In [116]:
hdl_col_df.describe()

absorbance0  ...  hdl_cholesterol_human_x0_ok
count  13140.000000  ...                 13140.000000
mean       0.507347  ...                     0.570776
std        0.042075  ...                     0.494984
min        0.237409  ...                     0.000000
25%        0.485665  ...                     0.000000
50%        0.510919  ...                     1.000000
75%        0.528750  ...                     1.000000
max        0.657782  ...                     1.000000

[8 rows x 175 columns]

In [117]:
minmax=MinMaxScaler()
minmax.fit(hdl_col_df.iloc[:,1:])
data_transform=minmax.transform(hdl_col_df.iloc[:,1:])

In [118]:
X=data_transform[:,:-3]
y_hdl_col=hdl_col_df.iloc[:,-3:]
y_hemo=hemo_df.iloc[:,-3:]
y_hemo=hemo_df.iloc[:,-3:]
y_col=col_df.iloc[:,-3:]

In [119]:
import tensorflow as tf
from keras.layers import InputLayer, Dense, LSTM, Input, Dropout,Embedding, Flatten,LayerNormalization
from keras.models import Sequential, Model

import keras.optimizers
from tensorflow.keras.callbacks import ModelCheckpoint
from keras.backend import clear_session
from tensorflow.keras.losses import mean_absolute_percentage_error, huber,kld,mse

from keras.preprocessing.sequence import pad_sequences

In [220]:
def blood_model():
    #clear_session()



    input_len=len(X[0])

    print(input_len)
    output_size=3
    drop_frac0=0.0 
    drop_frac1=0.0



    input1=Input(shape=(input_len,),)

    #flatt=Flatten()(lstm1)

    non=42
    #initializer = tf.keras.initializers.LecunNormal()
    #initializer=tf.keras.initializers.LecunUniform()
    #initializer=tf.keras.initializers.HeUniform(    seed=None)
    #initializer= tf.keras.initializers.RandomNormal(    mean=3.0, stddev=0.05, seed=None)

    initializer="normal"
    d1=Dense(7,activation="selu",kernel_initializer=initializer,input_dim=input_len,name="bottle")(input1)
    d1=Dropout(drop_frac0)(d1)
    


    pred=Dense(input_len,activation="selu")(d1)

    model = Model(inputs=input1, outputs=pred)

    opt = tf.keras.optimizers.Adamax(learning_rate=0.01)


    #lossfn = tf.keras.metrics.MSE()

    model.compile(loss="MSE",
        optimizer=opt,
        metrics=["MSE"])
    return(model)

In [221]:
!rm *.hdf5

In [222]:
model_name="encoder"
bestmodelname=""
def scheduler(epoch, lr):
    return 0.001

callback_LR = tf.keras.callbacks.LearningRateScheduler(scheduler)

def save_best_model_name():
    bestmodelname=model_name+"f_{val_MSE:.5f}_.hdf5"

callbacks =[
            callback_LR,
        
            ModelCheckpoint(filepath=model_name+"_{val_MSE:.5f}_.hdf5", monitor='val_MSE',
                        verbose=1, save_best_only=True, mode='min'),
           
        ]

In [223]:
full_model=blood_model()

172


In [224]:
save_best_model_name()

In [225]:
bestmodelname

''

In [227]:
full_model.fit(X,
          X,
          epochs=450, 
          batch_size=32,
          validation_split=0.2,
          verbose=1,
          callbacks=callbacks,
          shuffle=True
          
          )

Epoch 1/450
318/329 [===========================>..] - ETA: 0s - loss: 2.1004e-04 - MSE: 2.1004e-04
Epoch 00001: val_MSE did not improve from 0.00021
329/329 [==============================] - 1s 5ms/step - loss: 2.1004e-04 - MSE: 2.1004e-04 - val_loss: 2.0979e-04 - val_MSE: 2.0979e-04 - lr: 0.0010
Epoch 2/450
325/329 [============================>.] - ETA: 0s - loss: 2.0956e-04 - MSE: 2.0956e-04
Epoch 00002: val_MSE did not improve from 0.00021
329/329 [==============================] - 2s 5ms/step - loss: 2.0967e-04 - MSE: 2.0967e-04 - val_loss: 2.1018e-04 - val_MSE: 2.1018e-04 - lr: 0.0010
Epoch 3/450
329/329 [==============================] - ETA: 0s - loss: 2.0951e-04 - MSE: 2.0951e-04
Epoch 00003: val_MSE did not improve from 0.00021
329/329 [==============================] - 2s 5ms/step - loss: 2.0951e-04 - MSE: 2.0951e-04 - val_loss: 2.0980e-04 - val_MSE: 2.0980e-04 - lr: 0.0010
Epoch 4/450
318/329 [===========================>..] - ETA: 0s - loss: 2.0942e-04 - MSE: 2.0942e-04


In [228]:
X[0]

array([0.57629797, 0.56316263, 0.56058608, 0.55348446, 0.55432924,
       0.52801177, 0.52429853, 0.50529651, 0.49396945, 0.4908818 ,
       0.47677241, 0.47466856, 0.46398309, 0.46296189, 0.45314056,
       0.4461359 , 0.44496283, 0.44416027, 0.43586569, 0.43853278,
       0.43820073, 0.43619613, 0.43587531, 0.43594288, 0.42574665,
       0.43109712, 0.43362324, 0.43267825, 0.42976148, 0.43394287,
       0.43184588, 0.43866202, 0.4327672 , 0.431208  , 0.43553574,
       0.4331199 , 0.43502257, 0.4306428 , 0.43040646, 0.42566461,
       0.42792858, 0.42574241, 0.42172644, 0.42014705, 0.41649629,
       0.40968119, 0.4075168 , 0.40835163, 0.40112821, 0.39484841,
       0.39387877, 0.38614882, 0.38647705, 0.38217006, 0.37493735,
       0.3699833 , 0.36920971, 0.36554815, 0.36796923, 0.37310292,
       0.36670567, 0.36726969, 0.36314847, 0.36048029, 0.35013203,
       0.34812045, 0.34701882, 0.34821374, 0.34586192, 0.34227702,
       0.33816833, 0.33752315, 0.3293699 , 0.32742852, 0.32797

In [229]:
full_model_bottle=Model(full_model.inputs,full_model.get_layer("bottle").output)




In [230]:
full_pred_bottle=full_model_bottle.predict(X)



In [231]:
full_pred_bottle

array([[ 0.73612803, -0.18728596,  1.1215092 , ..., -0.2059155 ,
         0.78768754,  0.5842162 ],
       [ 0.71795666, -0.24121678,  1.7137302 , ..., -0.13969636,
         0.9261125 ,  0.7858857 ],
       [ 0.77321607, -0.27385622,  1.5683258 , ..., -0.22148277,
         0.4820413 ,  0.4825989 ],
       ...,
       [ 1.2888013 , -0.250663  ,  1.887331  , ...,  0.01227529,
         0.5899405 ,  0.88422656],
       [ 0.9488216 , -0.16394228,  0.6836511 , ..., -0.16270256,
         0.12849388,  0.36808652],
       [ 0.97089726, -0.30241537,  2.0494888 , ..., -0.18110922,
         0.69242835,  0.84945154]], dtype=float32)

In [232]:
df_bottle=pd.DataFrame()
df_bottle["summary"]=df["hdl_cholesterol_human"]+"+"+df["hemoglobin(hgb)_human"]+"+"+df["cholesterol_ldl_human"]


In [233]:
def cosine_similarity(x, y):
    return np.dot(x, y) / (np.sqrt(np.dot(x, x)) * np.sqrt(np.dot(y, y)))

In [234]:
# def a search matrix
def create_search_list(pred,df,str_index):
    out=[]
    for i,vec in enumerate(pred):
        out.append([vec,df[str_index].values[i]])
    return(out)
    
    

In [235]:
def generate_similarity(it1,sim_table):
    out=[]
    for it2 in sim_table:
        
        diff=cosine_similarity(it1,it2[0])
        if 1-diff<0.006:
            
            out.append(it2[1])
    return(out)

In [236]:
def find_max(dict):
    max=0
    sum=0
    outkey=""
    for key in dict.keys():
        akt=dict[key]
        sum+=akt
        if max<akt:
            max=akt
            outkey=key
    return outkey,max

In [237]:
def statistic(a):
    c=list(set(a))
    #print(c)
    out={}
    for i in c:
        out[i]=a.count(i)
    return(out)

In [238]:
full_bottle_list=create_search_list(full_pred_bottle,df_bottle,"summary")

In [239]:
import numpy as np




In [240]:
def calc_status(pred,dfcolumn):
    i=0
    for index,element in enumerate(pred):

        if element != dfcolumn.iloc[index]:
            #print(f"{index}")
            i +=1
    print(f"{i} hibás, {i/len(pred)*100} % hiba")        

In [241]:
# submission generation
!rm "./Test.csv"

In [242]:
!wget https://github.com/sipocz/Blood/raw/9326effc5771a0f4cbeef5d97e329c986c9ba9dd/orig/Test.csv

--2021-12-05 17:08:31--  https://github.com/sipocz/Blood/raw/9326effc5771a0f4cbeef5d97e329c986c9ba9dd/orig/Test.csv
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/sipocz/Blood/9326effc5771a0f4cbeef5d97e329c986c9ba9dd/orig/Test.csv [following]
--2021-12-05 17:08:31--  https://raw.githubusercontent.com/sipocz/Blood/9326effc5771a0f4cbeef5d97e329c986c9ba9dd/orig/Test.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10299206 (9.8M) [text/plain]
Saving to: ‘Test.csv’

Test.csv            100%[===================>]   9.82M  --.-KB/s    in 0.1s    

2021-12-05 17:08:32 (74.2 MB/s) - ‘Test.csv’ saved

In [243]:
test_df=pd.read_csv("./Test.csv")
test_df.head()

test_df['hdl_cholesterol_human']=0
test_df["hemoglobin(hgb)_human"]=0
test_df["cholesterol_ldl_human"]=0

In [244]:
test_transform=minmax.transform(test_df.iloc[:,1:])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:488: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- cholesterol_ldl_human
- hdl_cholesterol_human
- hemoglobin(hgb)_human
Feature names seen at fit time, yet now missing:
- hdl_cholesterol_human_x0_high
- hdl_cholesterol_human_x0_low
- hdl_cholesterol_human_x0_ok

  warnings.warn(message, FutureWarning)


In [245]:
X_test=test_transform[:,:-3]

In [246]:
# load models
from keras.models import load_model
base_path="./"

bottle_name=base_path+"encoder_0.00020_.hdf5"

bottle_model=load_model(bottle_name)


In [247]:
bottle_pred_test=full_model_bottle.predict(X_test)


In [248]:
bottle_pred_test[0]

array([ 1.0610826 , -0.09461067,  0.9018101 , -0.03815306, -0.2768333 ,
       -0.17918582,  0.4432311 ], dtype=float32)

In [249]:
full_predicted_test=[]


In [250]:
test_result=[]
db=0
for test_i in bottle_pred_test:
    o1=generate_similarity( test_i, full_bottle_list)
    result,_=find_max(statistic(o1))
    if result=="":
        result="NaN"
    db+=1
    if (db % 100)==0:
        print("...")
    print(result,end=",")
    test_result.append(result)

NaN,ok+ok+ok,NaN,NaN,ok+ok+ok,low+ok+high,ok+ok+ok,NaN,high+ok+high,low+ok+ok,NaN,high+ok+ok,low+ok+low,NaN,ok+ok+ok,ok+ok+ok,NaN,ok+ok+ok,ok+ok+ok,ok+ok+ok,ok+ok+ok,ok+ok+ok,ok+ok+high,NaN,NaN,ok+ok+ok,ok+ok+high,ok+ok+ok,ok+ok+ok,ok+ok+ok,low+ok+ok,low+ok+ok,ok+ok+high,ok+ok+ok,NaN,ok+ok+ok,ok+ok+ok,NaN,NaN,ok+ok+ok,ok+ok+ok,low+low+ok,ok+ok+ok,low+ok+ok,NaN,low+low+high,ok+ok+high,low+ok+ok,ok+ok+ok,ok+ok+high,low+low+high,ok+low+high,high+ok+ok,ok+ok+ok,high+ok+high,ok+ok+ok,ok+ok+high,low+ok+ok,ok+ok+ok,ok+ok+high,high+ok+ok,ok+ok+ok,high+ok+ok,ok+ok+high,ok+ok+ok,low+ok+low,ok+ok+high,low+ok+ok,ok+ok+ok,NaN,low+ok+ok,ok+ok+ok,NaN,ok+ok+high,ok+low+ok,low+ok+low,high+ok+ok,ok+ok+high,ok+ok+high,ok+ok+ok,ok+ok+ok,ok+ok+ok,ok+ok+ok,low+high+low,ok+ok+ok,ok+ok+ok,ok+ok+ok,ok+ok+ok,ok+ok+high,ok+ok+high,low+ok+ok,ok+ok+ok,ok+ok+ok,ok+ok+ok,ok+low+high,low+ok+ok,ok+ok+high,ok+ok+ok,ok+ok+ok,...
high+ok+high,ok+ok+ok,ok+ok+ok,low+ok+ok,high+ok+ok,NaN,NaN,ok+ok+ok,ok+ok+ok,NaN,ok+ok+high

In [251]:
def de_conv(pred):
    out0=[]
    out1=[]
    out2=[]

    for p in pred:
        if p=="NaN":
            p="ok+ok+ok"
        
        out0.append(p.split("+")[0])
        out1.append(p.split("+")[1])
        out2.append(p.split("+")[2])
        
    return(out0,out1,out2)

In [252]:
ret0,ret1,ret2=de_conv(test_result)

In [253]:
outdf=pd.DataFrame()
outdf["Reading_ID"]=test_df["Reading_ID"]
outdf["hdl_cholesterol_human"]=ret0
outdf["hemoglobin(hgb)_human"]=ret1
outdf["cholesterol_ldl_human"]=ret2

outdf.set_index("Reading_ID",inplace=True)

In [254]:
outdf.head(1)

hdl_cholesterol_human hemoglobin(hgb)_human cholesterol_ldl_human
Reading_ID                                                                   
ID_37BEI22R                    ok                    ok                    ok

In [255]:
!rm SampleSubmission.csv
!wget https://github.com/sipocz/Blood/raw/9326effc5771a0f4cbeef5d97e329c986c9ba9dd/orig/SampleSubmission.csv

--2021-12-05 17:17:25--  https://github.com/sipocz/Blood/raw/9326effc5771a0f4cbeef5d97e329c986c9ba9dd/orig/SampleSubmission.csv
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/sipocz/Blood/9326effc5771a0f4cbeef5d97e329c986c9ba9dd/orig/SampleSubmission.csv [following]
--2021-12-05 17:17:25--  https://raw.githubusercontent.com/sipocz/Blood/9326effc5771a0f4cbeef5d97e329c986c9ba9dd/orig/SampleSubmission.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 384318 (375K) [text/plain]
Saving to: ‘SampleSubmission.csv’

SampleSubmission.cs 100%[===================>] 375.31K  --.-KB/s    in 0.03s   

2021

In [256]:
submission_df=pd.read_csv("./SampleSubmission.csv")

In [257]:
for i in submission_df.index:
    #print(i)
    indexer=submission_df.loc[i,"Reading_ID"]

    splitter=indexer.split("_",2)
    out_index=splitter[0]+"_"+splitter[1]
    col_index=splitter[2]
    #print(out_index)
    result=outdf.loc[out_index][col_index]
    submission_df.iloc[i,1]=result

In [258]:
submission_df.set_index("Reading_ID", inplace=True)

In [259]:
def create_submission_name(project):
    from datetime  import datetime
    strdate=datetime.now().strftime("%Y%m%d_%H%M%S")
    out=project+"_"+"submission"+"_"+strdate+".csv"
    return(out)

In [260]:
submission_fname=create_submission_name("BloodAI")

In [261]:
submission_fname

'BloodAI_submission_20211205_171730.csv'

In [262]:
submission_df.to_csv(submission_fname,index=True)