<a href="https://colab.research.google.com/github/sipocz/Blood/blob/main/lazyregressor_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install lazypredict


In [2]:
import pandas as pd

from sklearn.preprocessing import MinMaxScaler

In [3]:
fname_url="https://github.com/sipocz/Blood/raw/b5fc44c487b0a712d00865014203349fb8690257/orig/train.zip"
fname=fname_url.split("/")[-1]

In [4]:
!wget $fname_url


--2021-12-06 19:14:31--  https://github.com/sipocz/Blood/raw/b5fc44c487b0a712d00865014203349fb8690257/orig/train.zip
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/sipocz/Blood/b5fc44c487b0a712d00865014203349fb8690257/orig/train.zip [following]
--2021-12-06 19:14:31--  https://raw.githubusercontent.com/sipocz/Blood/b5fc44c487b0a712d00865014203349fb8690257/orig/train.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16979362 (16M) [application/zip]
Saving to: ‘train.zip’

train.zip           100%[===================>]  16.19M  --.-KB/s    in 0.09s   

2021-12-06 19:14:32 (175 MB/s) - ‘train.zi

In [5]:
!mkdir "train"
!rm ./train/Train.csv

rm: cannot remove './train/Train.csv': No such file or directory


In [6]:
!unzip $fname -d "./train"
!rm train.zip

Archive:  train.zip
  inflating: ./train/Train.csv       


In [7]:
fname_train="./train/Train.csv"
df=pd.read_csv(fname_train)

In [8]:
df.head(5)

Reading_ID  absorbance0  ...  hemoglobin(hgb)_human  cholesterol_ldl_human
0  ID_3SSHI56C     0.479669  ...                     ok                     ok
1  ID_599OOLZA     0.471537  ...                   high                   high
2  ID_MVJGPQ75     0.444998  ...                     ok                   high
3  ID_CK6RF8YV     0.513434  ...                     ok                   high
4  ID_82N6QE6I     0.510485  ...                     ok                   high

[5 rows x 176 columns]

In [107]:
def one_hot_encode_df(df,str_index):
    from sklearn.preprocessing import OneHotEncoder
    indf=df.copy(True)
    one_hot=OneHotEncoder()
    col=indf[str_index].values
    col=col.reshape(-1,1)
    one_hot.fit(col)
    out=one_hot.transform(col).toarray()
    codes=one_hot.get_feature_names()
    print(codes)
    for ind,code in enumerate(codes):
        print("Itt:",ind,codes[ind])
        indf[str_index+"_"+code]=out[:,ind]
    return(indf,one_hot)

In [108]:
df,hdl_onehot=one_hot_encode_df(df,"hdl_cholesterol_human")
df,hemo_onehot=one_hot_encode_df(df,"hemoglobin(hgb)_human")
df,col_onehot=one_hot_encode_df(df,"cholesterol_ldl_human")

['x0_high' 'x0_low' 'x0_ok']
Itt: 0 x0_high
Itt: 1 x0_low
Itt: 2 x0_ok
['x0_high' 'x0_low' 'x0_ok']
Itt: 0 x0_high
Itt: 1 x0_low
Itt: 2 x0_ok
['x0_high' 'x0_low' 'x0_ok']
Itt: 0 x0_high
Itt: 1 x0_low
Itt: 2 x0_ok


In [109]:
df.tail()

Reading_ID  ...  cholesterol_ldl_human_x0_ok
13135  ID_NGPC0DA3  ...                         1.00
13136  ID_XRBUD5U8  ...                         1.00
13137  ID_2M9L5NV2  ...                         1.00
13138  ID_C5V5SD2D  ...                         1.00
13139  ID_9R5ZR9NX  ...                         0.00

[5 rows x 185 columns]

In [111]:

del df["hdl_cholesterol_human"]
del df["hemoglobin(hgb)_human"]
del df["cholesterol_ldl_human"]




In [112]:
from lazypredict.Supervised import LazyRegressor
from lazypredict.Supervised import LazyClassifier

from sklearn import datasets
from sklearn.utils import shuffle
import numpy as np


In [116]:
col_names=df.columns[-9:]

In [118]:
col_names[0]

'hdl_cholesterol_human_x0_high'

In [119]:
X=df.iloc[:,1:-9]
y=df.loc[:,col_names[0]]

0       0.00
1       0.00
2       0.00
3       0.00
4       0.00
        ... 
13135   1.00
13136   0.00
13137   0.00
13138   0.00
13139   1.00
Name: hdl_cholesterol_human_x0_high, Length: 13140, dtype: float64

In [122]:
X

absorbance0  absorbance1  ...  temperature  humidity
0             0.48         0.48  ...        42.51     34.01
1             0.47         0.47  ...        44.52     32.09
2             0.44         0.46  ...        45.77     24.80
3             0.51         0.51  ...        45.84     36.93
4             0.51         0.52  ...        38.92     23.88
...            ...          ...  ...          ...       ...
13135         0.48         0.48  ...        34.79     36.93
13136         0.53         0.53  ...        43.12     19.14
13137         0.51         0.52  ...        42.48     43.41
13138         0.46         0.47  ...        41.86     35.10
13139         0.50         0.50  ...        42.91     26.30

[13140 rows x 172 columns]

In [121]:
offset=int(0.9*len(X))
print(offset)

11826


In [95]:
X_train, y_train = X[:offset], y[:offset]
X_test, y_test = X[offset:], y[offset:]

clf = LazyClassifier(verbose=1,ignore_warnings=True, custom_metric=None,predictions=True)
modells,predictions = clf.fit(X_train, X_test, y_train, y_test)


  0%|          | 0/29 [00:03<?, ?it/s]


KeyboardInterrupt: ignored

In [126]:
t1=KNeighborsClassifier()
o=t1.fit(X_train,y_train)

In [133]:
y_train

hdl_cholesterol_human_x0_ok
0                             1.00
1                             1.00
2                             1.00
3                             0.00
4                             1.00
...                            ...
11821                         0.00
11822                         1.00
11823                         1.00
11824                         1.00
11825                         1.00

[11826 rows x 1 columns]

In [134]:
o.predict

array([0., 1., 0., ..., 1., 1., 1.])

In [147]:
from sklearn.neighbors import  KNeighborsClassifier
my_cl=[]

for i in range(9):

    my_cl.append(  KNeighborsClassifier())
    X=df.iloc[:,1:-9]
    y=df.loc[:,col_names[i]]
    my_cl[i].fit(X,y)



In [148]:
my_cl

[KNeighborsClassifier(),
 KNeighborsClassifier(),
 KNeighborsClassifier(),
 KNeighborsClassifier(),
 KNeighborsClassifier(),
 KNeighborsClassifier(),
 KNeighborsClassifier(),
 KNeighborsClassifier(),
 KNeighborsClassifier()]

In [149]:
my_cl[0].predict(X)

array([0., 0., 0., ..., 0., 0., 1.])

In [150]:
my_cl[1].predict(X)

array([0., 0., 0., ..., 0., 0., 0.])

In [151]:
my_cl[2].predict(X)

array([1., 1., 1., ..., 1., 1., 0.])