In [1]:
#!pip install lazypredict

In [2]:
__PROJECT_SOURCE__="COLAB"

In [3]:
if __PROJECT_SOURCE__=="COLAB":
    # Import PyDrive and associated libraries.
    # This only needs to be done once per notebook.
    from pydrive.auth import GoogleAuth
    from pydrive.drive import GoogleDrive
    from google.colab import auth
    from oauth2client.client import GoogleCredentials

    # Authenticate and create the PyDrive client.
    # This only needs to be done once per notebook.
    auth.authenticate_user()
    gauth = GoogleAuth()
    gauth.credentials = GoogleCredentials.get_application_default()
    drive = GoogleDrive(gauth)
    from google.colab import drive
    drive.mount('/content/drive')
    fname_dir="/content/blood/"
    fname_url="/content/drive/MyDrive/blood/rework/*agg.csv"
    fname=fname_url.split("/")[-1]
elif __PROJECT_SOURCE__=="LOCAL":
    fname_dir="sdfsdfsd" #working dir
    fname_url="/content/drive/MyDrive/blood/rework/*agg.csv" #data source dir
    


Mounted at /content/drive


In [4]:
!mkdir $fname_dir

mkdir: cannot create directory ‘/content/blood/’: File exists


In [5]:
!cp $fname_url $fname_dir

In [6]:
if __PROJECT_SOURCE__=="COLAB":
    drive.flush_and_unmount()
    print('Unmount Google Drive :-(')

Unmount Google Drive :-(


## Feldolgozás

In [7]:
!rm *.hdf5

rm: cannot remove '*.hdf5': No such file or directory


In [8]:
import pandas as pd

In [9]:
fnames_list=["ldl1_agg.csv","ldl2_agg.csv"]

In [10]:
file_name1=fname_dir+fnames_list[0]
print(file_name1)

/content/blood/ldl1_agg.csv


In [11]:
file_name2=fname_dir+fnames_list[1]
print(file_name2)

/content/blood/ldl2_agg.csv


In [12]:
df_agg1= pd.read_csv(file_name1)
df_agg1.describe()
df_agg1.drop(df_agg1[df_agg1.absorbance0 < 0].index, inplace=True) # kill the negative elements


In [13]:
df_agg1.head()

Unnamed: 0  absorbance0  ...  cholesterol_ldl_value  cholesterol_ldl_human
0           0     0.535147  ...                  105.6                      1
1           1     0.538019  ...                   72.4                      1
2           2     0.480685  ...                   68.4                      1
3           3     0.505587  ...                  106.0                      1
4           4     0.546671  ...                   31.2                      0

[5 rows x 176 columns]

In [14]:
df_agg2= pd.read_csv(file_name2)
df_agg2.describe()
df_agg2.drop(df_agg2[df_agg2.absorbance0 < 0].index, inplace=True) # kill the negative elements


In [15]:
df_agg=pd.concat([df_agg1,df_agg2], ignore_index=True)

In [16]:
df_agg.tail()

Unnamed: 0  absorbance0  ...  cholesterol_ldl_value  cholesterol_ldl_human
537         405     0.559508  ...               88.54285                      1
538         406     0.587427  ...              159.68645                      3
539         407     0.477241  ...               99.20000                      1
540         408     0.565670  ...              164.71290                      3
541         409     0.462006  ...               98.99000                      1

[5 rows x 176 columns]

In [17]:
df_agg.describe()

Unnamed: 0  absorbance0  ...  cholesterol_ldl_value  cholesterol_ldl_human
count  542.000000   542.000000  ...             542.000000             542.000000
mean   170.702952     0.520451  ...             111.436592               1.485240
std    120.507914     0.040351  ...              44.306810               1.031287
min      0.000000     0.400606  ...               5.300000               0.000000
25%     68.000000     0.492162  ...              81.347500               1.000000
50%    136.500000     0.517637  ...             109.850000               1.000000
75%    273.750000     0.545690  ...             136.480000               3.000000
max    409.000000     0.696677  ...             310.800000               3.000000

[8 rows x 176 columns]

In [18]:

import tensorflow as tf
from keras.layers import InputLayer, Dense, LSTM, Input, Dropout,Embedding, Flatten,LayerNormalization
from keras.models import Sequential, Model

import keras.optimizers
from tensorflow.keras.callbacks import ModelCheckpoint
from keras.backend import clear_session
from tensorflow.keras.losses import mean_absolute_percentage_error, huber,kld,mse

from keras.preprocessing.sequence import pad_sequences
import numpy as np


In [19]:
X_columns=df_agg.columns[1:-5]
y_columns=df_agg.columns[-1] # the category is at the end of columns
X_=df_agg[X_columns]
y_=df_agg[y_columns]

In [20]:
X_columns

Index(['absorbance0', 'absorbance1', 'absorbance2', 'absorbance3',
       'absorbance4', 'absorbance5', 'absorbance6', 'absorbance7',
       'absorbance8', 'absorbance9',
       ...
       'absorbance160', 'absorbance161', 'absorbance162', 'absorbance163',
       'absorbance164', 'absorbance165', 'absorbance166', 'absorbance167',
       'absorbance168', 'absorbance169'],
      dtype='object', length=170)

In [21]:
y_.replace(3,2, inplace=True) # the generated file contains  0,1,3 as the category label :-( 

In [22]:
#y_.replace(2,0, inplace=True)

In [23]:
y_=np.array(y_)

In [24]:
y_=y_.reshape(-1,1)

In [25]:
y_columns

'cholesterol_ldl_human'

In [26]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

X_columns=df_agg.columns[1:-5]
y_columns=df_agg.columns[-1] # the category is at the end of columns
X_=df_agg[X_columns]
y_=df_agg[y_columns]

y_.replace(3,2, inplace=True) # the generated file contains  0,1,3 as the category label :-( 

y_=np.array(y_)
y_=y_.reshape(-1,1)



__X_SCALER__="normal"

__DNN_MODE__="regression"

__Y_SCALER__="normal"

if __DNN_MODE__=="regression":
    y_columns=df_agg.columns[-2] # the category is at the  -2  column
    y_=df_agg[y_columns]
    y_=np.array(y_)
    y_=y_.reshape(-1,1)


elif __DNN_MODE__=="classification":
    y_columns=df_agg.columns[-1] # the category is at the end of columns
    y_=df_agg[y_columns]
    y_.replace(3,2, inplace=True) # the generated file contains  0,1,3 as the category label :-( 
    y_=np.array(y_)
    y_=y_.reshape(-1,1)

y=y_
print(y[0:10])

if __X_SCALER__=="normal":
    X_normalizer = StandardScaler() 
    X=X_normalizer.fit_transform(X_)

if __Y_SCALER__=="normal":
    y_normalizer = StandardScaler() 
    y=y_normalizer.fit_transform(y_,)
    print(f"Itt: {y}")

if __X_SCALER__=="minmax":
    X_minmax = MinMaxScaler() 
    X=X_minmax.fit_transform(X_)

if __Y_SCALER__=="minmax":
    y_minmax = MinMaxScaler() 
    y=y_minmax.fit_transform(y_)
    




[[105.6]
 [ 72.4]
 [ 68.4]
 [106. ]
 [ 31.2]
 [ 40.6]
 [ 82.6]
 [ 32.7]
 [ 64.2]
 [151. ]]
Itt: [[-0.13185294]
 [-0.88186563]
 [-0.97222861]
 [-0.12281665]
 [-1.81260428]
 [-1.60025128]
 [-0.65144005]
 [-1.77871816]
 [-1.06710973]
 [ 0.89376682]
 [-0.37583298]
 [-0.74180302]
 [-0.01438108]
 [ 0.83051274]
 [-0.65144005]
 [ 0.42387935]
 [ 2.26276589]
 [-1.33819866]
 [-0.45715965]
 [-1.66802352]
 [ 0.22959896]
 [ 0.0669456 ]
 [ 0.07146375]
 [ 0.15279043]
 [-0.75083932]
 [-0.19510703]
 [ 1.73866064]
 [ 0.595569  ]
 [ 0.50972418]
 [ 1.21907353]
 [-0.36679668]
 [-0.97674676]
 [ 1.04286573]
 [ 1.04286573]
 [-0.84572044]
 [-0.72824858]
 [ 0.81244014]
 [ 0.17086302]
 [ 0.93443016]
 [ 0.3524926 ]
 [-0.3035426 ]
 [-1.50175564]
 [-1.09015229]
 [-0.10881038]
 [-0.58411963]
 [-0.03064641]
 [-0.5619807 ]
 [-0.4494788 ]
 [ 0.24496066]
 [-1.44663423]
 [ 0.13291057]
 [-0.19962517]
 [-0.01618834]
 [-1.03051273]
 [-2.13700736]
 [-0.14540739]
 [ 0.07959642]
 [ 0.6927092 ]
 [-0.86831119]
 [-0.59722226]
 [ 0

In [27]:
y_normalizer.get_params()

{'copy': True, 'with_mean': True, 'with_std': True}

In [28]:
y

array([[-0.13185294],
       [-0.88186563],
       [-0.97222861],
       [-0.12281665],
       [-1.81260428],
       [-1.60025128],
       [-0.65144005],
       [-1.77871816],
       [-1.06710973],
       [ 0.89376682],
       [-0.37583298],
       [-0.74180302],
       [-0.01438108],
       [ 0.83051274],
       [-0.65144005],
       [ 0.42387935],
       [ 2.26276589],
       [-1.33819866],
       [-0.45715965],
       [-1.66802352],
       [ 0.22959896],
       [ 0.0669456 ],
       [ 0.07146375],
       [ 0.15279043],
       [-0.75083932],
       [-0.19510703],
       [ 1.73866064],
       [ 0.595569  ],
       [ 0.50972418],
       [ 1.21907353],
       [-0.36679668],
       [-0.97674676],
       [ 1.04286573],
       [ 1.04286573],
       [-0.84572044],
       [-0.72824858],
       [ 0.81244014],
       [ 0.17086302],
       [ 0.93443016],
       [ 0.3524926 ],
       [-0.3035426 ],
       [-1.50175564],
       [-1.09015229],
       [-0.10881038],
       [-0.58411963],
       [-0

In [29]:
'''
import wandb
from wandb.keras import WandbCallback

wandb.init(config={"hyper": "parameter"})
'''



'\nimport wandb\nfrom wandb.keras import WandbCallback\n\nwandb.init(config={"hyper": "parameter"})\n'

In [30]:
def blood_model_2():
    #clear_session()

    keras.backend.clear_session()

    input_len=170

    print(input_len)
    output_size=24
    drop_frac0=0.0 
    drop_frac1=0.0



    input1=Input(shape=(input_len,))

    #flatt=Flatten()(lstm1)

    non=42
    #initializer = tf.keras.initializers.LecunNormal()
    #initializer=tf.keras.initializers.LecunUniform()
    #initializer=tf.keras.initializers.HeUniform(    seed=None)
    #initializer= tf.keras.initializers.RandomNormal(    mean=3.0, stddev=0.05, seed=None)

    initializer="HeNormal"
    d1=Dense(1000,activation="sigmoid",kernel_initializer=initializer)(input1)
    d1=Dense(100,activation="sigmoid",kernel_initializer=initializer)(d1)
    #d1=Dense(100,activation="selu",kernel_initializer=initializer)(d1)


    #softmax
    pred=Dense(1,activation="sigmoid",)(d1)

    
    
    model = Model(inputs=input1, outputs=pred)

    opt = tf.keras.optimizers.Adamax(learning_rate=0.001)


    lossfn = tf.keras.metrics.SparseCategoricalCrossentropy()

    model.compile(loss="CategoricalCrossentropy",
        optimizer=opt,
        metrics=["Accuracy"])
    return(model)

array([[-0.13185294],
       [-0.88186563],
       [-0.97222861],
       [-0.12281665],
       [-1.81260428],
       [-1.60025128],
       [-0.65144005],
       [-1.77871816],
       [-1.06710973],
       [ 0.89376682],
       [-0.37583298],
       [-0.74180302],
       [-0.01438108],
       [ 0.83051274],
       [-0.65144005],
       [ 0.42387935],
       [ 2.26276589],
       [-1.33819866],
       [-0.45715965],
       [-1.66802352],
       [ 0.22959896],
       [ 0.0669456 ],
       [ 0.07146375],
       [ 0.15279043],
       [-0.75083932],
       [-0.19510703],
       [ 1.73866064],
       [ 0.595569  ],
       [ 0.50972418],
       [ 1.21907353],
       [-0.36679668],
       [-0.97674676],
       [ 1.04286573],
       [ 1.04286573],
       [-0.84572044],
       [-0.72824858],
       [ 0.81244014],
       [ 0.17086302],
       [ 0.93443016],
       [ 0.3524926 ],
       [-0.3035426 ],
       [-1.50175564],
       [-1.09015229],
       [-0.10881038],
       [-0.58411963],
       [-0

In [32]:
!pip install wandb
!wandb login

wandb: Currently logged in as: sipoczlaszlo (use `wandb login --relogin` to force relogin)


In [102]:
import wandb
from wandb.keras import WandbCallback

wandb.init(project="Blood_Measure_Normalized", entity="sipoczlaszlo")

In [103]:
def blood_model_regression():
    #clear_session()

    keras.backend.clear_session()

    input_len=170

    print(input_len)
    output_size=24
    drop_frac0=0.05 
    drop_frac1=0.05



    input1=Input(shape=(input_len,))

    #flatt=Flatten()(lstm1)

    non=42
    #initializer = tf.keras.initializers.LecunNormal()
    #initializer=tf.keras.initializers.LecunUniform()
    #initializer=tf.keras.initializers.HeUniform(    seed=None)
    #initializer= tf.keras.initializers.RandomNormal(    mean=3.0, stddev=0.05, seed=None)

    initializer="normal"
    d1=Dense(500,activation="relu",kernel_initializer=initializer)(input1)
    d1=Dropout(drop_frac0)(d1)
    
    d1=Dense(250,activation="tanh",kernel_initializer=initializer)(d1)
   

    #softmax
    pred=Dense(1, kernel_initializer=initializer)(d1)

    
    
    model = Model(inputs=input1, outputs=pred)

    opt = tf.keras.optimizers.SGD(learning_rate=0.0000001)


    lossfn = tf.keras.metrics.SparseCategoricalCrossentropy()

    model.compile(loss="MSE",
        optimizer=opt,
        metrics=["MSE"])
    return(model)

In [104]:
__DNN_MODE__

'regression'

In [105]:
if __DNN_MODE__=="classification":
    model_name="classification_"
    def scheduler(epoch, lr):
        return 0.001

    callback_LR = tf.keras.callbacks.LearningRateScheduler(scheduler)

    callbacks = [callback_LR,
            
            #savemodela,
            ModelCheckpoint(filepath=model_name+"_{loss:.5f}_{val_loss:.5f}_.hdf5", monitor='val_loss',
                            verbose=1, save_best_only=True, mode='min')]



In [106]:
if __DNN_MODE__=="regression":
    model_name="regression_"
    def scheduler(epoch, lr):
        if epoch<50:
            return 0.01
        elif epoch <500:
            return 0.005


    callback_LR = tf.keras.callbacks.LearningRateScheduler(scheduler)

    callbacks = [callback_LR,
            
            #savemodela,
            ModelCheckpoint(filepath=model_name+"_{loss:.5f}_{val_loss:.5f}_.hdf5", monitor='val_loss',
                            verbose=1, save_best_only=True, mode='min')]



In [107]:
if __DNN_MODE__=="classification":
    new_model_2=blood_model_2()

In [108]:
if __DNN_MODE__=="regression":
    new_model_2=blood_model_regression()

170


In [109]:
!rm *.hdf5

In [110]:
X

array([[ 0.36453647,  0.38885105,  0.39872672, ...,  1.82445842,
         1.673298  ,  1.92809129],
       [ 0.43579244,  0.39694511,  0.40961367, ...,  0.57719086,
         0.45474503,  0.32195174],
       [-0.9863988 , -0.96168426, -0.90536406, ...,  0.21397963,
         0.08306335,  0.19148561],
       ...,
       [-1.07183495, -1.01721066, -1.05299893, ..., -1.18797608,
        -1.15115283, -1.14202762],
       [ 1.12166936,  1.0612296 ,  1.09288581, ..., -0.09962229,
        -0.02788948, -0.05773341],
       [-1.44973193, -1.46461933, -1.4970304 , ..., -1.13059767,
        -1.05839207, -1.05836683]])

In [ ]:
if __DNN_MODE__=="regression":
    new_model_2.summary()
    history=new_model_2.fit(X,
          y,
          epochs=1000, 
          batch_size=3,
          validation_split=0.2,
          verbose=1,
          callbacks=[callbacks,WandbCallback()],
          shuffle=True
          
          )


Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 170)]             0         
                                                                 
 dense (Dense)               (None, 500)               85500     
                                                                 
 dropout (Dropout)           (None, 500)               0         
                                                                 
 dense_1 (Dense)             (None, 250)               125250    
                                                                 
 dense_2 (Dense)             (None, 1)                 251       
                                                                 
Total params: 211,001
Trainable params: 211,001
Non-trainable params: 0
_________________________________________________________________
Epoch 1/1000
145/145 [==============================] -

In [ ]:
---

In [ ]:
#new_model_2.load_weights("./_col_0.00098_0.00173_.xhdf5")

In [ ]:
new_model_2.load_weights("./regression__0.04629_0.03222_.hdf5")

In [ ]:
y_pred=new_model_2.predict(X)
result_df=pd.DataFrame()
y_pred_col=[i[0] for i in y_pred]
y_col=[i[0] for i in y]

result_df["y"]=y_col
result_df["y_pred"]=y_pred_col

In [ ]:
import plotly.express as px

fig = px.scatter(result_df, x="y", y="y_pred",width=600, height=400 )
fig.show()

In [ ]:
---

In [ ]:


from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score,mean_absolute_error


clf = RandomForestRegressor(max_depth=70, random_state=0,n_estimators=300)
clf.fit(X_train, y_train)

randomforest_predict=clf.predict(X_train)


In [ ]:
print(f"Accuracy: {mean_absolute_error(y_train,randomforest_predict)}")

In [ ]:
randomforest_predict=clf.predict(X_test)
print(f"Accuracy: {mean_absolute_error(y_test,randomforest_predict)}")

In [ ]:
---

In [ ]:
y

In [ ]:
clf = LazyClassifier(verbose=1,ignore_warnings=True, custom_metric=None)
models,predictions = clf.fit(X[:-100], X[-100:], y[:-100], y[-100:])

In [ ]:
print(models)

In [ ]:
yo=[i[0] for i in y_]
yo

In [ ]:
X

In [ ]:
from lazypredict.Supervised import LazyRegressor
reg = LazyRegressor(verbose=2, ignore_warnings=False, custom_metric=None)
models,predictions = clf.fit(X[:-100], X[-100:], y[:-100], y[-100:])

In [ ]:
print(models)

In [ ]:
x_counter=1

In [ ]:
X_train=X[:-1*x_counter]
X_test=X[-1*x_counter:]
y_train=yo[:-1*x_counter]
y_test =yo[-1*x_counter:]
